(function(g){var window=this;var IHa=function(a,b){return g.Mb(a,b)},k4=function(a,b,c){a.l.set(b,c)},l4=function(a){k4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Ta()).toString(36));
return a},m4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Sm(a.l,b,c)},JHa=function(a,b){var c=[];
g.Xi(b,function(d){try{var e=g.Fn.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.En(e)&&c.push(d)},a);
return c},KHa=function(a,b){var c=JHa(a,b);
g.Ab(c,function(d){g.Fn.prototype.remove.call(this,d)},a)},LHa=function(a){if(a.W){if(a.W.locationOverrideToken)return{locationOverrideToken:a.W.locationOverrideToken};
if(null!=a.W.latitudeE7&&null!=a.W.longitudeE7)return{latitudeE7:a.W.latitudeE7,longitudeE7:a.W.longitudeE7}}return null},MHa=function(a,b){g.fb(a,b)||a.push(b)},n4=function(a){var b=0,c;
for(c in a)b++;return b},NHa=function(a,b){var c=b instanceof g.Gc?b:g.Mc(b,/^data:image\//i.test(b));
a.src=g.Hc(c)},OHa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},PHa=function(a){if(a.sg&&"function"==typeof a.sg)return a.sg();
if("string"===typeof a)return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Jb(a)},QHa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||"string"===typeof a)g.Ab(a,b,void 0);else{if(a.sh&&"function"==typeof a.sh)var c=a.sh();else if(a.sg&&"function"==typeof a.sg)c=void 0;else if(g.Na(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Kb(a);d=PHa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},RHa=function(a,b,c,d){var e=new g.Gm(null,void 0);
a&&g.Hm(e,a);b&&g.Im(e,b);c&&g.Jm(e,c);d&&(e.J=d);return e},o4=function(){},p4=function(a,b){g.vo[a]=!0;
var c=g.to();c&&c.publish.apply(c,arguments);g.vo[a]=!1},q4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Dm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",SHa(this,a.capabilities||""),THa(this,a.experiments||""))},SHa=function(a,b){a.capabilities.clear();
g.Ne(b.split(","),g.Ra(IHa,UHa)).forEach(function(c){a.capabilities.add(c)})},THa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},r4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},s4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},VHa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},WHa=function(a){return new r4(a)},XHa=function(a){return Array.isArray(a)?g.Qc(a,WHa):[]},t4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},u4=function(a){return Array.isArray(a)?"["+g.Qc(a,t4).join(",")+"]":"null"},v4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},YHa=function(a){return g.Qc(a,function(b){return{key:b.id,
name:b.name}})},w4=function(a,b){return g.cb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},x4=function(a,b){return g.cb(a,function(c){return s4(c,b)})},ZHa=function(){var a=(0,g.Eu)();
a&&KHa(a,a.i.Oj(!0))},y4=function(){var a=g.Hu("yt-remote-connected-devices")||[];
g.xb(a);return a},$Ha=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Qc(a,function(d,e){return 0==e?d:d.substring(c.length)})},aIa=function(a){g.Gu("yt-remote-connected-devices",a,86400)},A4=function(){if(z4)return z4;
var a=g.Hu("yt-remote-device-id");a||(a=v4(),g.Gu("yt-remote-device-id",a,31536E3));for(var b=y4(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return z4=d},B4=function(){var a=y4(),b=A4();
g.fb(a,b);g.Ju()&&g.zb(a,b);a=$Ha(a);if(g.gb(a))try{g.Mq("remote_sid")}catch(c){}else try{g.Kq("remote_sid",a.join(","),-1)}catch(c){}},bIa=function(){return g.Hu("yt-remote-session-browser-channel")},cIa=function(){return g.Hu("yt-remote-local-screens")||[]},dIa=function(){g.Gu("yt-remote-lounge-token-expiration",!0,86400)},eIa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Qc(cIa(),function(d){return d.loungeToken}),c=g.Qc(a,function(d){return d.loungeToken});
g.ah(c,function(d){return!g.fb(b,d)})&&dIa();
g.Gu("yt-remote-local-screens",a,31536E3)},fIa=function(a,b){g.Gu("yt-remote-session-browser-channel",a);
g.Gu("yt-remote-session-screen-id",b);var c=y4(),d=A4();g.fb(c,d)||c.push(d);aIa(c);B4()},C4=function(a){a||(g.Iu("yt-remote-session-screen-id"),g.Iu("yt-remote-session-video-id"));
B4();a=y4();g.kb(a,A4());aIa(a)},gIa=function(){if(!D4){var a=g.Pn();
a&&(D4=new g.zn(a))}},hIa=function(){gIa();
return D4?!!D4.get("yt-remote-use-staging-server"):!1},E4=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},iIa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},jIa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},F4=function(a){a.length?kIa(a.shift(),function(){F4(a)}):G4()},lIa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},kIa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.nd(d,g.fg(a));(document.head||document.documentElement).appendChild(d)},mIa=function(){var a=E4(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},G4=function(){var a=jIa();
a&&a(!1,"No cast extension found")},H4=function(){if(nIa){var a=2,b=jIa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;kIa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",G4,c)}},oIa=function(){H4();
var a=mIa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");F4(a)},qIa=function(){H4();
var a=mIa();a.push.apply(a,g.ma(pIa.map(lIa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");F4(a)},I4=function(a,b,c){g.E.call(this);
this.I=null!=c?(0,g.C)(a,c):a;this.Jf=b;this.C=(0,g.C)(this.QJ,this);this.i=!1;this.l=0;this.u=this.ib=null;this.B=[]},J4=function(a,b,c){g.E.call(this);
this.B=null!=c?a.bind(c):a;this.Jf=b;this.u=null;this.i=!1;this.l=0;this.ib=null},K4=function(a){a.ib=g.Bm(function(){a.ib=null;
a.i&&!a.l&&(a.i=!1,K4(a))},a.Jf);
var b=a.u;a.u=null;a.B.apply(null,b)},L4=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return OHa(a)},M4=function(){},N4=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},P4=function(a){O4.dispatchEvent(new rIa(O4,a))},rIa=function(a,b){g.xl.call(this,"statevent",a);
this.stat=b},Q4=function(){},sIa=function(){},uIa=function(a){return(a=tIa(a))?new ActiveXObject(a):new XMLHttpRequest},tIa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},R4=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.C_(this);this.u=new g.Am;this.u.setInterval(250)},wIa=function(a,b,c){a.zp=1;
a.Sk=l4(b.clone());a.Cn=c;a.I=!0;vIa(a,null)},S4=function(a,b,c,d,e){a.zp=1;
a.Sk=l4(b.clone());a.Cn=null;a.I=c;e&&(a.TG=!1);vIa(a,d)},vIa=function(a,b){a.lp=Date.now();
T4(a);a.Ql=a.Sk.clone();m4(a.Ql,"t",a.J);a.Es=0;a.Be=a.i.Ax(a.i.ds()?b:null);0<a.xw&&(a.Su=new J4((0,g.C)(a.NH,a,a.Be),a.xw));a.B.ya(a.Be,"readystatechange",a.ZP);var c=a.im?g.Vb(a.im):{};a.Cn?(a.Gv="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Be.send(a.Ql,a.Gv,a.Cn,c)):(a.Gv="GET",a.TG&&!g.De&&(c.Connection="close"),a.Be.send(a.Ql,a.Gv,null,c));a.i.hi(1)},zIa=function(a,b,c){for(var d=!0;!a.Lm&&a.Es<c.length;){var e=xIa(a,c);
if(e==U4){4==b&&(a.Mk=4,P4(15),d=!1);break}else if(e==yIa){a.Mk=4;P4(16);d=!1;break}else V4(a,e)}4==b&&0==c.length&&(a.Mk=1,P4(17),d=!1);a.Ai=a.Ai&&d;d||(W4(a),X4(a))},xIa=function(a,b){var c=a.Es,d=b.indexOf("\n",c);
if(-1==d)return U4;c=Number(b.substring(c,d));if(isNaN(c))return yIa;d+=1;if(d+c>b.length)return U4;var e=b.substr(d,c);a.Es=d+c;return e},BIa=function(a,b){a.lp=Date.now();
T4(a);var c=b?window.location.hostname:"";a.Ql=a.Sk.clone();k4(a.Ql,"DOMAIN",c);k4(a.Ql,"t",a.J);try{a.Ei=new ActiveXObject("htmlfile")}catch(n){W4(a);a.Mk=7;P4(22);X4(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in Y4)h=Y4[h];else if(h in AIa)h=Y4[h]=AIa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
Y4[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.kd(g.hc("b/12014412"),d+"</body></html>");a.Ei.open();a.Ei.write(g.gd(c));a.Ei.close();a.Ei.parentWindow.m=(0,g.C)(a.wP,a);a.Ei.parentWindow.d=(0,g.C)(a.cG,a,!0);a.Ei.parentWindow.rpcClose=(0,g.C)(a.cG,a,!1);c=a.Ei.createElement("DIV");a.Ei.parentWindow.document.body.appendChild(c);d=g.Lc(a.Ql.toString());d=g.sd(g.Hc(d));d=g.kd(g.hc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ld(c,d);a.i.hi(1)},T4=function(a){a.OA=Date.now()+
a.C;
CIa(a,a.C)},CIa=function(a,b){if(null!=a.Fp)throw Error("WatchDog timer not null");
a.Fp=N4((0,g.C)(a.EP,a),b)},Z4=function(a){a.Fp&&(g.A.clearTimeout(a.Fp),a.Fp=null)},X4=function(a){a.i.LB()||a.Lm||a.i.Ts(a)},W4=function(a){Z4(a);
g.zi(a.Su);a.Su=null;a.u.stop();g.ACa(a.B);if(a.Be){var b=a.Be;a.Be=null;b.abort();b.dispose()}a.Ei&&(a.Ei=null)},V4=function(a,b){try{a.i.TF(a,b),a.i.hi(4)}catch(c){}},EIa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;DIa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){EIa(a,b,c,d,f)},f)})}},DIa=function(a,b,c){var d=new Image;
d.onload=function(){try{$4(d),c(!0)}catch(e){}};
d.onerror=function(){try{$4(d),c(!1)}catch(e){}};
d.onabort=function(){try{$4(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{$4(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
NHa(d,a)},$4=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},a5=function(a){g.Rl.call(this);
this.headers=new g.Dm;this.ea=a||null;this.B=!1;this.ca=this.i=null;this.za=this.W="";this.I=0;this.u="";this.C=this.la=this.L=this.ga=!1;this.J=0;this.X=null;this.Da="";this.Y=this.ia=!1},FIa=function(a){return g.Be&&g.be(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},GIa=function(a){return"content-type"==a.toLowerCase()},IIa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.I=5;HIa(a);b5(a)},HIa=function(a){a.ga||(a.ga=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},KIa=function(a){if(a.B&&"undefined"!=typeof g.F_)if(a.ca[1]&&4==c5(a)&&2==a.getStatus())d5(a,"Local request error detected and ignored");
else if(a.L&&4==c5(a))g.Bm(a.QF,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){d5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Bd(1,String(a.W));if(!f&&g.A.self&&g.A.self.location){var h=g.A.self.location.protocol;f=h.substr(0,h.length-1)}e=!JIa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<c5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";HIa(a)}}finally{b5(a)}}},b5=function(a,b){if(a.i){LIa(a);
var c=a.i,d=a.ca[0]?g.Ka:null;a.i=null;a.ca=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},LIa=function(a){a.i&&a.Y&&(a.i.ontimeout=null);
a.X&&(g.A.clearTimeout(a.X),a.X=null)},c5=function(a){return a.i?a.i.readyState:0},e5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},d5=function(a,b){return b+" ["+a.za+" "+a.W+" "+a.getStatus()+"]"},MIa=function(a){this.i=a;
this.l=new M4},NIa=function(a){var b=f5(a.i,a.mq,"/mail/images/cleardot.gif");
l4(b);EIa(b.toString(),5E3,(0,g.C)(a.GK,a),3,2E3);a.hi(1)},h5=function(a){var b=a.i.L;
if(null!=b)P4(5),b?(P4(11),g5(a.i,a,!1)):(P4(12),g5(a.i,a,!0));else if(a.Cg=new R4(a,void 0,void 0,void 0),a.Cg.im=a.yw,b=a.i,b=f5(b,b.ds()?a.bq:null,a.zw),P4(5),!g.Be||g.de(10))m4(b,"TYPE","xmlhttp"),S4(a.Cg,b,!1,a.bq,!1);else{m4(b,"TYPE","html");var c=a.Cg;a=!!a.bq;c.zp=3;c.Sk=l4(b.clone());BIa(c,a)}},i5=function(a,b,c){this.Ma=1;
this.i=[];this.u=[];this.B=new M4;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},OIa=function(a,b){this.i=a;
this.map=b;this.context=null},PIa=function(a,b,c,d){g.xl.call(this,"timingevent",a);
this.size=b;this.Tr=d},QIa=function(a){g.xl.call(this,"serverreachability",a)},TIa=function(a){RIa(a);
if(3==a.Ma){var b=a.zr++,c=a.At.clone();k4(c,"SID",a.l);k4(c,"RID",b);k4(c,"TYPE","terminate");j5(a,c);b=new R4(a,a.l,b,void 0);b.zp=2;b.Sk=l4(c.clone());NHa(new Image,b.Sk.toString());b.lp=Date.now();T4(b)}SIa(a)},UIa=function(a){a.aL(1,0);
a.At=f5(a,null,a.Aw);k5(a)},RIa=function(a){a.Wk&&(a.Wk.abort(),a.Wk=null);
a.Xd&&(a.Xd.cancel(),a.Xd=null);a.Qj&&(g.A.clearTimeout(a.Qj),a.Qj=null);l5(a);a.pg&&(a.pg.cancel(),a.pg=null);a.jl&&(g.A.clearTimeout(a.jl),a.jl=null)},VIa=function(a,b){if(0==a.Ma)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new OIa(a.vM++,b));2!=a.Ma&&3!=a.Ma||k5(a)},WIa=function(a){var b=0;
a.Xd&&b++;a.pg&&b++;return b},k5=function(a){a.pg||a.jl||(a.jl=N4((0,g.C)(a.aG,a),0),a.wo=0)},YIa=function(a,b){if(1==a.Ma){if(!b){a.zr=Math.floor(1E5*Math.random());
var c=a.zr++,d=new R4(a,"",c,void 0);d.im=a.Ki;var e=m5(a),f=a.At.clone();k4(f,"RID",c);k4(f,"CVER","1");j5(a,f);wIa(d,f,e);a.pg=d;a.Ma=2}}else 3==a.Ma&&(b?XIa(a,b):0==a.i.length||a.pg||XIa(a))},XIa=function(a,b){if(b)if(6<a.Mm){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.zr-1;var d=m5(a)}else c=b.L,d=b.Cn;else c=a.zr++,d=m5(a);var e=a.At.clone();k4(e,"SID",a.l);k4(e,"RID",c);k4(e,"AID",a.Po);j5(a,e);c=new R4(a,a.l,c,a.wo+1);c.im=a.Ki;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.pg=c;wIa(c,e,d)},j5=function(a,b){if(a.Bf){var c=a.Bf.xD();
c&&g.Cb(c,function(d,e){k4(b,e,d)})}},m5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Mm&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Sn:e.Sn},f++){e.Sn=a.i[f].i;var h=a.i[f].map;e.Sn=6>=a.Mm?f:e.Sn-d;try{g.Cb(h,function(l){return function(m,n){c.push("req"+l.Sn+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Sn+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},ZIa=function(a){a.Xd||a.Qj||(a.I=1,a.Qj=N4((0,g.C)(a.ZF,a),0),a.ho=0)},n5=function(a){if(a.Xd||a.Qj||3<=a.ho)return!1;
a.I++;a.Qj=N4((0,g.C)(a.ZF,a),$Ia(a,a.ho));a.ho++;return!0},g5=function(a,b,c){a.Ev=c;
a.Li=b.Mj;a.C||UIa(a)},l5=function(a){null!=a.Um&&(g.A.clearTimeout(a.Um),a.Um=null)},$Ia=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},o5=function(a,b){if(2==b||9==b){var c=null;
a.Bf&&(c=null);var d=(0,g.C)(a.GQ,a);c||(c=new g.Gm("//www.google.com/images/cleardot.gif"),l4(c));DIa(c.toString(),1E4,d)}else P4(2);aJa(a,b)},aJa=function(a,b){a.Ma=0;
a.Bf&&a.Bf.MC(b);SIa(a);RIa(a)},SIa=function(a){a.Ma=0;
a.Li=-1;if(a.Bf)if(0==a.u.length&&0==a.i.length)a.Bf.jx();else{g.ob(a.u);var b=g.ob(a.i);a.u.length=0;a.i.length=0;a.Bf.jx(b)}},f5=function(a,b,c){var d=g.Om(c);
if(""!=d.i)b&&g.Im(d,b+"."+d.i),g.Jm(d,d.u);else{var e=window.location;d=RHa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Fq&&g.Cb(a.Fq,function(f,h){k4(d,h,f)});
k4(d,"VER",a.Mm);j5(a,d);return d},bJa=function(){},cJa=function(){this.i=[];
this.l=[]},dJa=function(a,b){this.action=a;
this.params=b||{}},p5=function(a,b){g.E.call(this);
this.i=new g.J(this.oP,0,this);g.I(this,this.i);this.Jf=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.C)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.C)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},q5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ca=a;this.I=b;this.u=new g.yn;this.l=new p5(this.jQ,this);this.i=null;this.X=!1;this.C=null;this.W="";this.L=this.B=0;this.J=[];this.ea=c;this.Y=d;this.ia=e},eJa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Ev,sessionId:a.i.l,arrayId:a.i.Po}},fJa=function(a,b){a.L=b||0;
a.l.stop();r5(a);a.i&&(3==a.i.getState()&&YIa(a.i),TIa(a.i));a.L=0},s5=function(a){return!!a.i&&3==a.i.getState()},r5=function(a){if(a.i){var b=a.Y(),c=a.i.Ki||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Ki=c}},t5=function(a){this.scheme="https";
this.port=this.domain="";this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.Bd(4,a))||"";b&&(this.port=":"+b);this.domain=g.Cd(a)||"";a=g.Wc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ec(a,"10.0")&&(this.l=!1))},u5=function(a,b){var c=a.i;
a.l&&(c=a.scheme+"://"+a.domain+a.port+a.i);return g.Od(c+b,{})},v5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.B,d,!0),onError:g.Ra(a.u,e),onTimeout:g.Ra(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Pp(b,a)},jJa=function(){var a=gJa;
hJa();w5.push(a);iJa()},x5=function(a,b){hJa();
var c=kJa(a,String(b));g.gb(w5)?lJa(c):(iJa(),g.Ab(w5,function(d){d(c)}))},hJa=function(){w5||(w5=g.Ja("yt.mdx.remote.debug.handlers_")||[],g.Ea("yt.mdx.remote.debug.handlers_",w5,void 0))},lJa=function(a){var b=(y5+1)%50;
y5=b;z5[b]=a;A5||(A5=49==b)},iJa=function(){var a=w5;
if(z5[0]){var b=A5?y5:-1;do{b=(b+1)%50;var c=z5[b];g.Ab(a,function(d){d(c)})}while(b!=y5);
z5=Array(50);y5=-1;A5=!1}},kJa=function(a,b){var c=(Date.now()-mJa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},B5=function(a){g.R.call(this);
this.I=a;this.screens=[]},nJa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},oJa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ne(a.screens,function(f){return!!w4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=nJa(a,b[d])||c;return c},pJa=function(a,b){var c=a.screens.length;
a.screens=g.Ne(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},C5=function(a,b,c,d,e){g.R.call(this);
this.u=a;this.J=b;this.B=c;this.I=d;this.C=e;this.l=0;this.i=null;this.ib=NaN},E5=function(a){B5.call(this,"LocalScreenService");
this.l=a;this.i=NaN;D5(this);this.info("Initializing with "+u4(this.screens))},qJa=function(a){if(a.screens.length){var b=g.Qc(a.screens,function(d){return d.id}),c=u5(a.l,"/pairing/get_lounge_token_batch");
v5(a.l,c,{screen_ids:b.join(",")},(0,g.C)(a.yL,a),(0,g.C)(a.xL,a))}},D5=function(a){if(g.Go("deprecate_pair_servlet_enabled"))return oJa(a,[]);
var b=XHa(cIa());b=g.Ne(b,function(c){return!c.uuid});
return oJa(a,b)},F5=function(a,b){eIa(g.Qc(a.screens,VHa));
b&&dIa()},H5=function(a,b){g.R.call(this);
this.I=b;var c=g.Hu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.fb(c,l)}this.i=d;this.C=a;this.u=this.B=NaN;this.l=null;G5("Initialized with "+g.yj(this.i))},I5=function(a,b,c){var d=u5(a.C,"/pairing/get_screen_availability");
v5(a.C,d,{lounge_token:b.token},(0,g.C)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.C)(function(){c(!1)},a))},J5=function(a,b){a:if(n4(b)!=n4(a.i))var c=!1;
else{c=g.Kb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(G5("Updated online screens: "+g.yj(a.i)),a.i=b,a.V("screenChange"));rJa(a)},K5=function(a){isNaN(a.u)||g.so(a.u);
a.u=g.qo((0,g.C)(a.Oz,a),0<a.B&&a.B<g.Ta()?2E4:1E4)},G5=function(a){x5("OnlineScreenService",a)},sJa=function(a){var b={};
g.Ab(a.I(),function(c){c.token?b[c.token]=c.id:this.Gd("Requesting availability of screen w/o lounge token.")});
return b},rJa=function(a){a=g.Kb(g.Db(a.i,function(b){return b}));
g.xb(a);a.length?g.Gu("yt-remote-online-screen-ids",a.join(","),60):g.Iu("yt-remote-online-screen-ids")},L5=function(a){B5.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.u=[];this.C={};tJa(this)},vJa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Lg();if(h=(c?x4(h,c):null)||x4(h,b)){h.uuid=b;var l=M5(a,h);I5(a.i,l,function(m){e(m?l:null)})}else c?uJa(a,c,(0,g.C)(function(m){var n=M5(this,new r4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));I5(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},wJa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},xJa=function(a,b,c){I5(a.i,b,c)},uJa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Pp(u5(a.B,"/pairing/get_lounge_token_batch"),e)},yJa=function(a){a.screens=a.l.Lg();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+u4(a.screens))},tJa=function(a){N5(a);
a.l=new E5(a.B);a.l.subscribe("screenChange",(0,g.C)(a.EL,a));yJa(a);a.u=XHa(g.Hu("yt-remote-automatic-screen-cache")||[]);N5(a);a.info("Initializing automatic screens: "+u4(a.u));a.i=new H5(a.B,(0,g.C)(a.Lg,a,!0));a.i.subscribe("screenChange",(0,g.C)(function(){this.V("onlineScreenChange")},a))},M5=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=x4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),zJa(a));N5(a);a.C[b.uuid]=b.id;g.Gu("yt-remote-device-id-map",a.C,31536E3);return b},zJa=function(a){a=g.Ne(a.u,function(b){return"shortLived"!=b.idType});
g.Gu("yt-remote-automatic-screen-cache",g.Qc(a,VHa))},N5=function(a){a.C=g.Hu("yt-remote-device-id-map")||{}},O5=function(a,b,c){g.R.call(this);
this.ia=c;this.u=a;this.i=b;this.B=null},P5=function(a,b){a.B=b;
a.V("sessionScreen",a.B)},AJa=function(a,b){a.B&&(a.B.token=b,M5(a.u,a.B));
a.V("sessionScreen",a.B)},Q5=function(a,b){x5(a.ia,b)},R5=function(a,b,c){O5.call(this,a,b,"CastSession");
var d=this;this.ga=c;this.l=null;this.Y=(0,g.C)(this.VJ,this);this.ea=(0,g.C)(this.IP,this);this.X=g.qo(function(){BJa(d,null)},12E4);
this.J=this.C=this.I=this.L=0;this.ca=!1;this.W="unknown"},S5=function(a,b){g.so(a.J);
a.J=0;0==b?CJa(a):a.J=g.qo(function(){CJa(a)},b)},CJa=function(a){DJa(a,"getLoungeToken");
g.so(a.C);a.C=g.qo(function(){EJa(a,null)},3E4)},DJa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.yj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ka,(0,g.C)(function(){Q5(this,"Failed to send message: "+b+".")},a)):Q5(a,"Sending yt message without session: "+g.yj(c))},T5=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.MD(b,function(c){P5(a,c)},function(){return a.cg()},5)):a.cg(Error("Waiting for session status timed out."))},GJa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new r4(b);FJa(a,d,function(e){e?(a.ca=!0,M5(a.u,d),P5(a,d),a.W="unknown",S5(a,c)):(g.no(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.cg())},5)},BJa=function(a,b){g.so(a.X);
a.X=0;b?a.ga.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?GJa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.no(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),T5(a,b.screenId))):(g.no(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),
T5(a,b.screenId)):T5(a,b.screenId):a.cg(Error("Waiting for session status timed out."))},EJa=function(a,b){g.so(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.W=c,S5(a,3E4)):(AJa(a,b.loungeToken),a.ca=!1,a.W="unknown",S5(a,b.loungeTokenRefreshIntervalMs))},FJa=function(a,b,c,d){g.so(a.I);
a.I=0;xJa(a.u,b,function(e){e||0>d?c(e):a.I=g.qo(function(){FJa(a,b,c,d-1)},300)})},HJa=function(a){g.so(a.L);
a.L=0;g.so(a.I);a.I=0;g.so(a.X);a.X=0;g.so(a.C);a.C=0;g.so(a.J);a.J=0},U5=function(a,b,c,d){O5.call(this,a,b,"DialSession");
this.ma=d;this.l=this.L=null;this.ea="";this.za=c;this.la=null;this.X=g.Ka;this.W=NaN;this.ga=(0,g.C)(this.WJ,this);this.C=g.Ka;this.J=this.I=0;this.Y=!1;this.ca="unknown"},V5=function(a){var b;
return!!(a.ma.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},IJa=function(a){a.C=a.u.NB(a.ea,a.i.label,a.i.friendlyName,V5(a),function(b,c){a.C=g.Ka;
a.Y=!0;P5(a,b);"shortLived"==b.idType&&0<c&&W5(a,c)},function(b){a.C=g.Ka;
a.cg(b)})},JJa=function(a){var b={};
b.pairingCode=a.ea;b.theme=a.za;hIa()&&(b.env_useStageMdx=1);return g.Md(b)},X5=function(a){return new Promise(function(b){a.ea=v4();
if(a.la){var c=new chrome.cast.DialLaunchResponse(!0,JJa(a));b(c);IJa(a)}else a.X=function(){g.so(a.W);a.X=function(){};
a.W=NaN;var d=new chrome.cast.DialLaunchResponse(!0,JJa(a));b(d);IJa(a)},a.W=g.qo(function(){a.X()},100)})},LJa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new r4(b);return(new Promise(function(e){KJa(a,d,function(f){f?(a.Y=!0,M5(a.u,d),P5(a,d),W5(a,c)):g.no(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):X5(a)})},MJa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){vJa(a.u,c,b,d,function(f){f&&f.token&&P5(a,f);e(f)},function(f){Q5(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):X5(a)})},KJa=function(a,b,c,d){g.so(a.I);
a.I=0;xJa(a.u,b,function(e){e||0>d?c(e):a.I=g.qo(function(){KJa(a,b,c,d-1)},300)})},W5=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
V5(a)&&(g.so(a.J),a.J=0,0==b?NJa(a):a.J=g.qo(function(){NJa(a)},b))},NJa=function(a){V5(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ca=c,W5(a,3E4)):(a.Y=!1,a.ca="unknown",AJa(a,b.loungeToken),W5(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ca="noLoungeTokenResponse";W5(a,3E4)})},OJa=function(a){g.so(a.I);
a.I=0;g.so(a.J);a.J=0;a.C();a.C=function(){};
g.so(a.W)},Y5=function(a,b){O5.call(this,a,b,"ManualSession");
this.l=g.qo((0,g.C)(this.Qo,this,null),150)},Z5=function(a,b){g.R.call(this);
this.B=b;this.l=a;this.L=b.appId||"233637DE";this.C=b.theme||"cl";this.W=b.disableCastApi||!1;this.i=null;this.J=!1;this.u=[];this.I=(0,g.C)(this.EO,this)},PJa=function(a,b){return b?g.cb(a.u,function(c){return s4(b,c.label)},a):null},$5=function(a){x5("Controller",a)},gJa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},a6=function(a){return a.J||!!a.u.length||!!a.i},b6=function(a,b,c){b!=a.i&&(g.zi(a.i),(a.i=b)?(c?a.V("yt-remote-cast2-receiver-resumed",
b.i):a.V("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.C)(a.XF,a,b)),b.getScreen()?a.V("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Qo(null)):a.V("yt-remote-cast2-session-change",null))},QJa=function(a){var b=a.l.MB(),c=a.i&&a.i.i;
a=g.Qc(b,function(d){c&&s4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=PJa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},VJa=function(a,b,c,d){d.disableCastApi?c6("Cannot initialize because disabled by Mdx config."):RJa()?SJa(b,d)&&(d6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?TJa(a,c):(window.__onGCastApiAvailable=function(e,f){e?TJa(a,c):(e6("Failed to load cast API: "+f),f6(!1),d6(!1),g.Iu("yt-remote-cast-available"),g.Iu("yt-remote-cast-receiver"),
UJa(),c(!1))},d.loadCastApiSetupScript?g.Co("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=E4()&&oIa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?G4():89<=E4()?qIa():(H4(),F4(pIa.map(lIa))))):c6("Cannot initialize because not running Chrome")},UJa=function(){c6("dispose");
var a=g6();a&&a.dispose();g.Ea("yt.mdx.remote.cloudview.instance_",null,void 0);WJa(!1);g.yo(h6);h6.length=0},i6=function(){return!!g.Hu("yt-remote-cast-installed")},XJa=function(){var a=g.Hu("yt-remote-cast-receiver");
return a?a.friendlyName:null},YJa=function(){c6("clearCurrentReceiver");
g.Iu("yt-remote-cast-receiver")},ZJa=function(){return i6()?g6()?g6().getCastSession():(e6("getCastSelector: Cast is not initialized."),null):(e6("getCastSelector: Cast API is not installed!"),null)},k6=function(){i6()?g6()?j6()?(c6("Requesting cast selector."),g6().requestSession()):(c6("Wait for cast API to be ready to request the session."),h6.push(g.xo("yt-remote-cast2-api-ready",k6))):e6("requestCastSelector: Cast is not initialized."):e6("requestCastSelector: Cast API is not installed!")},l6=
function(a,b){j6()?g6().setConnectedScreenStatus(a,b):e6("setConnectedScreenStatus called before ready.")},RJa=function(){var a=0<=g.Wc.search(/ (CrMo|Chrome|CriOS)\//);
return g.FA||a},$Ja=function(a,b){g6().init(a,b)},SJa=function(a,b){var c=!1;
g6()||(c=new Z5(a,b),c.subscribe("yt-remote-cast2-availability-change",function(d){g.Gu("yt-remote-cast-available",d);p4("yt-remote-cast2-availability-change",d)}),c.subscribe("yt-remote-cast2-receiver-selected",function(d){c6("onReceiverSelected: "+d.friendlyName);
g.Gu("yt-remote-cast-receiver",d);p4("yt-remote-cast2-receiver-selected",d)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(d){c6("onReceiverResumed: "+d.friendlyName);
g.Gu("yt-remote-cast-receiver",d);p4("yt-remote-cast2-receiver-resumed",d)}),c.subscribe("yt-remote-cast2-session-change",function(d){c6("onSessionChange: "+t4(d));
d||g.Iu("yt-remote-cast-receiver");p4("yt-remote-cast2-session-change",d)}),g.Ea("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
c6("cloudview.createSingleton_: "+c);return c},g6=function(){return g.Ja("yt.mdx.remote.cloudview.instance_")},TJa=function(a,b){f6(!0);
d6(!1);$Ja(a,function(c){c?(WJa(!0),g.zo("yt-remote-cast2-api-ready")):(e6("Failed to initialize cast API."),f6(!1),g.Iu("yt-remote-cast-available"),g.Iu("yt-remote-cast-receiver"),UJa());b(c)})},c6=function(a){x5("cloudview",a)},e6=function(a){x5("cloudview",a)},f6=function(a){c6("setCastInstalled_ "+a);
g.Gu("yt-remote-cast-installed",a)},j6=function(){return!!g.Ja("yt.mdx.remote.cloudview.apiReady_")},WJa=function(a){c6("setApiReady_ "+a);
g.Ea("yt.mdx.remote.cloudview.apiReady_",a,void 0)},d6=function(a){g.Ea("yt.mdx.remote.cloudview.initializing_",a,void 0)},m6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.J=this.L=0;this.i=null;this.hasNext=this.aj=!1;this.W=this.I=this.l=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},n6=function(a){a.audioTrackId=null;
a.i=null;a.playerState=-1;a.aj=!1;a.hasNext=!1;a.L=0;a.J=g.Ta();a.C=0;a.l=0;a.I=0;a.W=0;a.B=NaN;a.u=!1},o6=function(a){return a.Nb()?(g.Ta()-a.J)/1E3:0},p6=function(a,b){a.L=b;
a.J=g.Ta()},q6=function(a){switch(a.playerState){case 1:case 1081:return(g.Ta()-a.J)/1E3+a.L;
case -1E3:return 0}return a.L},r6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&n6(a)},s6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Wb(a.i);b.hasPrevious=a.aj;b.hasNext=a.hasNext;b.playerTime=a.L;b.playerTimeAt=a.J;b.seekableStart=a.C;b.seekableEnd=a.l;b.duration=a.I;b.loadedTime=a.W;b.liveIngestionTime=a.B;return b},u6=function(a,b){g.R.call(this);
this.Ma=0;this.u=a;this.C=[];this.B=new cJa;this.l=this.i=null;this.L=(0,g.C)(this.gN,this);this.I=(0,g.C)(this.Cr,this);this.J=(0,g.C)(this.fN,this);this.W=(0,g.C)(this.nN,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.cA,this),aKa(this))):c=3;0!=c&&(b?this.cA(c):g.qo((0,g.C)(function(){this.cA(c)},this),0));
var d=ZJa();d&&t6(this,d);this.subscribe("yt-remote-cast2-session-change",this.W)},v6=function(a){return new m6(a.u.getPlayerContextData())},aKa=function(a){g.Ab("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Ra(this.BO,b),this))},a)},bKa=function(a){g.Ab(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},w6=function(a){return 1==a.getState()},x6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},z6=function(a,b,c){var d=v6(a);
p6(d,c);-1E3!=d.playerState&&(d.playerState=b);y6(a,d)},A6=function(a,b,c){a.u.sendMessage(b,c)},y6=function(a,b){bKa(a);
a.u.setPlayerContextData(s6(b));aKa(a)},t6=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.I),a.Cr(null));
a.l=b;a.l&&(x5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.I),a.l.media.length&&a.Cr(a.l.media[0]))},cKa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=v6(a);b.contentId!=d.videoId&&x5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;p6(d,a.i.getEstimatedTime());y6(a,d)}else x5("CP","No cast media video. Ignoring state update.")},B6=function(a,b,c){return(0,g.C)(function(d){this.Gd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Gd("Retrying "+b+" using MDx browser channel."),A6(this,b,c))},a)},C6=function(a,b,c){g.R.call(this);
this.C=NaN;this.ca=!1;this.L=this.J=this.X=this.Y=NaN;this.W=[];this.B=this.I=this.u=this.Hb=this.i=null;this.ia=a;this.W.push(g.So(window,"beforeunload",(0,g.C)(this.sL,this)));this.l=[];this.Hb=new m6;this.ga=b.id;this.ea=b.idType;this.i=dKa(this,c);this.i.subscribe("handlerOpened",this.kN,this);this.i.subscribe("handlerClosed",this.hN,this);this.i.subscribe("handlerError",this.iN,this);this.i.subscribe("handlerMessage",this.jN,this);this.i.dv(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.Hb.videoId;g.Ju()&&g.Gu("yt-remote-session-video-id",d)},this)},D6=function(a){x5("conn",a)},dKa=function(a,b){return new q5(u5(a.ia,"/bc"),b,!1,function(){return a.RB()},"shortLived"==a.ea)},E6=function(a,b){a.V("proxyStateChange",b)},eKa=function(a){a.C=g.qo((0,g.C)(function(){D6("Connecting timeout");
this.ro(1)},a),2E4)},F6=function(a){g.so(a.C);
a.C=NaN},G6=function(a){g.so(a.Y);
a.Y=NaN},fKa=function(a){H6(a);
a.X=g.qo((0,g.C)(function(){I6(this,"getNowPlaying")},a),2E4)},H6=function(a){g.so(a.X);
a.X=NaN},hKa=function(a,b){b&&(F6(a),G6(a));
var c=s5(a.i)&&isNaN(a.C);b==c?b&&(E6(a,1),I6(a,"getSubtitlesTrack")):b?(a.LD()&&a.Hb.reset(),E6(a,1),I6(a,"getNowPlaying"),gKa(a)):a.ro(1)},iKa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Hb.videoId&&(g.Pb(b.params)?a.Hb.i=null:a.Hb.i=b.params,a.V("remotePlayerChange"))},jKa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Hb.listId=b.params.listId||a.Hb.listId;r6(a.Hb,c,d);a.V("remoteQueueChange")},lKa=function(a,b){b.params=b.params||{};
jKa(a,b);kKa(a,b);a.V("autoplayDismissed")},kKa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
p6(a.Hb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Hb.playerState&&(c=-1E3);a.Hb.playerState=c;c=Number(b.params.loadedTime);a.Hb.W=isNaN(c)?0:c;c=Number(b.params.duration);a.Hb.I=isNaN(c)?0:c;c=a.Hb;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.Hb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.l=isNaN(e)?0:e;1==a.Hb.playerState?fKa(a):H6(a);a.V("remotePlayerChange")},mKa=function(a,b){if(-1E3!=
a.Hb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Hb.playerState=c;c=parseInt(b.params.currentTime,10);p6(a.Hb,isNaN(c)?0:c);a.V("remotePlayerChange")}},nKa=function(a,b){var c="true"==b.params.muted;
a.Hb.volume=parseInt(b.params.volume,10);a.Hb.muted=c;a.V("remotePlayerChange")},oKa=function(a,b){a.I=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},pKa=function(a,b){var c="true"==b.params.hasNext;
a.Hb.aj="true"==b.params.hasPrevious;a.Hb.hasNext=c;a.V("previousNextChange")},gKa=function(a){g.so(a.L);
a.L=g.qo((0,g.C)(a.ro,a,1),864E5)},I6=function(a,b,c){c?D6("Sending: action="+b+", params="+g.yj(c)):D6("Sending: action="+b);
a.i.sendMessage(b,c)},J6=function(a){B5.call(this,"ScreenServiceProxy");
this.If=a;this.i=[];this.i.push(this.If.$_s("screenChange",(0,g.C)(this.aK,this)));this.i.push(this.If.$_s("onlineScreenChange",(0,g.C)(this.iO,this)))},tKa=function(a,b){gIa();
if(!D4||!D4.get("yt-remote-disable-remote-module-for-dev")){b=g.P("MDX_CONFIG")||b;ZHa();B4();K6||(K6=new t5(b?b.loungeApiHost:void 0),hIa()&&(K6.i="/api/loungedev"));L6||(L6=g.Ja("yt.mdx.remote.deferredProxies_")||[],g.Ea("yt.mdx.remote.deferredProxies_",L6,void 0));qKa();var c=M6();if(!c){var d=new L5(K6);g.Ea("yt.mdx.remote.screenService_",d,void 0);c=M6();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,disableCastApi:b.disableCastApi,
enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});VJa(a,d,function(h){h?N6()&&l6(N6(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){p4("yt-remote-receiver-availability-change")})},e)}if(b&&!g.Ja("yt.mdx.remote.initialized_")){g.Ea("yt.mdx.remote.initialized_",!0,void 0);
O6("Initializing: "+g.yj(b));P6.push(g.xo("yt-remote-cast2-availability-change",function(){p4("yt-remote-receiver-availability-change")}));
P6.push(g.xo("yt-remote-cast2-receiver-selected",function(){Q6(null);p4("yt-remote-auto-connect","cast-selector-receiver")}));
P6.push(g.xo("yt-remote-cast2-receiver-resumed",function(){p4("yt-remote-receiver-resumed","cast-selector-receiver")}));
P6.push(g.xo("yt-remote-cast2-session-change",rKa));P6.push(g.xo("yt-remote-connection-change",function(h){h?l6(N6(),"YouTube TV"):R6()||(l6(null,null),YJa())}));
e=S6();b.isAuto&&(e.id+="#dial");g.Go("desktop_enable_autoplay")&&(e.capabilities=["atp"]);e.name=b.device;e.app=b.app;var f=b.theme;f&&(e.theme=f);O6(" -- with channel params: "+g.yj(e));e?(g.Gu("yt-remote-session-app",e.app),g.Gu("yt-remote-session-name",e.name)):(g.Iu("yt-remote-session-app"),g.Iu("yt-remote-session-name"));g.Ea("yt.mdx.remote.channelParams_",e,void 0);c.start();N6()||sKa()}}},uKa=function(){var a=M6().If.$_gos();
var b=T6();b&&U6()&&(w4(a,b)||a.push(b));return YHa(a)},V6=function(){var a=vKa();
!a&&i6()&&XJa()&&(a={key:"cast-selector-receiver",name:XJa()});return a},vKa=function(){var a=uKa(),b=T6();
b||(b=R6());return g.cb(a,function(c){return b&&s4(b,c.key)?!0:!1})},T6=function(){var a=N6();
if(!a)return null;var b=M6().Lg();return x4(b,a)},rKa=function(a){O6("remote.onCastSessionChange_: "+t4(a));
if(a){var b=T6();if(b&&b.id==a.id){if(l6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))W6&&(W6.token=a),(b=U6())&&b.dv(a)}else b&&X6(),Y6(a,1)}else U6()&&X6()},X6=function(){j6()?g6().stopSession():e6("stopSession called before API ready.");
var a=U6();a&&(a.disconnect(1),Z6(null))},$6=function(){var a=U6();
return!!a&&3!=a.getProxyState()},O6=function(a){x5("remote",a)},M6=function(){if(!a7){var a=g.Ja("yt.mdx.remote.screenService_");
a7=a?new J6(a):null}return a7},N6=function(){return g.Ja("yt.mdx.remote.currentScreenId_")},wKa=function(a){g.Ea("yt.mdx.remote.currentScreenId_",a,void 0)},xKa=function(){return g.Ja("yt.mdx.remote.connectData_")},Q6=function(a){g.Ea("yt.mdx.remote.connectData_",a,void 0)},U6=function(){return g.Ja("yt.mdx.remote.connection_")},Z6=function(a){var b=U6();
Q6(null);a||wKa("");g.Ea("yt.mdx.remote.connection_",a,void 0);L6&&(g.Ab(L6,function(c){c(a)}),L6.length=0);
b&&!a?p4("yt-remote-connection-change",!1):!b&&a&&p4("yt-remote-connection-change",!0)},R6=function(){var a=g.Ju();
if(!a)return null;var b=M6();if(!b)return null;b=b.Lg();return x4(b,a)},Y6=function(a,b){N6();
T6()&&T6();if(b7)W6=a;else{wKa(a.id);var c=new C6(K6,a,S6());c.connect(b,xKa());c.subscribe("beforeDisconnect",function(d){p4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){U6()&&(U6(),Z6(null))});
c.subscribe("browserChannelAuthError",function(){var d=T6();d&&"shortLived"==d.idType&&(j6()?g6().handleBrowserChannelAuthError():e6("refreshLoungeToken called before API ready."))});
Z6(c)}},sKa=function(){var a=R6();
a?(O6("Resume connection to: "+t4(a)),Y6(a,0)):(C4(),YJa(),O6("Skipping connecting because no session screen found."))},qKa=function(){var a=S6();
if(g.Pb(a)){a=A4();var b=g.Hu("yt-remote-session-name")||"",c=g.Hu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ea("yt.mdx.remote.channelParams_",a,void 0)}},S6=function(){return g.Ja("yt.mdx.remote.channelParams_")||{}},c7=function(a,b,c){g.E.call(this);
var d=this;this.l=a;this.G=b;this.xb=c;this.events=new g.$M(this);this.X=this.events.N(this.G,"onVolumeChange",function(e){yKa(d,e)});
this.C=!1;this.suggestion=null;this.I=new g.dK(64);this.i=new g.J(this.bH,500,this);this.u=new g.J(this.cH,1E3,this);this.L=new I4(this.XQ,0,this);this.B={};this.W=new g.J(this.EH,1E3,this);this.J=new J4(this.seekTo,1E3,this);this.Y=g.Ka;g.I(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.RN);this.events.N(b,"captionschanged",this.dN);this.events.N(b,"captionssettingschanged",this.hH);this.events.N(b,"videoplayerreset",this.Mu);this.events.N(b,"mdxautoplaycancel",function(){d.xb.gD()});
a=this.xb;a.na();a.subscribe("proxyStateChange",this.SF,this);a.subscribe("remotePlayerChange",this.Ir,this);a.subscribe("remoteQueueChange",this.Mu,this);a.subscribe("previousNextChange",this.PF,this);a.subscribe("nowAutoplaying",this.JF,this);a.subscribe("autoplayDismissed",this.hF,this);g.I(this,this.i);g.I(this,this.u);g.I(this,this.L);g.I(this,this.W);g.I(this,this.J);this.hH();this.Mu();this.Ir()},yKa=function(a,b){if(d7(a)){a.xb.unsubscribe("remotePlayerChange",a.Ir,a);
var c=Math.round(b.volume),d=!!b.muted,e=v6(a.xb);if(c!==e.volume||d!==e.muted)a.xb.setVolume(c,d),a.W.start();a.xb.subscribe("remotePlayerChange",a.Ir,a)}},zKa=function(a){a.Db(0);
a.i.stop();a.ub(new g.dK(64))},e7=function(a,b){if(d7(a)&&!a.C){var c=null;
b&&(c={style:a.G.getSubtitlesUserSettings()},g.Yb(c,b));a.xb.QB(a.G.getVideoData(1).videoId,c);a.B=v6(a.xb).i}},f7=function(a,b){var c=a.G.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.G.getVideoData(1);a.xb.playVideo(c.videoId,b,d,e,c.playerParams,c.ga,LHa(c));a.ub(new g.dK(1))},AKa=function(a,b){if(b){var c=a.G.getOption("captions","tracklist",{eE:1});
c&&c.length?(a.G.setOption("captions","track",b),a.C=!1):(a.G.loadModule("captions"),a.C=!0)}else a.G.setOption("captions","track",{})},d7=function(a){return v6(a.xb).videoId===a.G.getVideoData(1).videoId},g7=function(){g.X.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",ba:"Connecting to your TV on web using a code will be going away soon"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",ka:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],ba:"Learn more"},{D:"button",ka:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],ba:"OK"}]}]}]});this.i=new g.NL(this,250);this.learnMoreButton=
this.ha("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ha("ytp-mdx-manual-pairing-popup-ok");g.I(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},h7=function(){g.X.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",ba:"You're signed out"},{D:"div",K:"ytp-mdx-popup-description",ba:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",ka:["ytp-button","ytp-mdx-privacy-popup-cancel"],ba:"Cancel"},{D:"button",ka:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],ba:"Confirm"}]}]}]});this.i=new g.NL(this,250);this.cancelButton=this.ha("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ha("ytp-mdx-privacy-popup-confirm");g.I(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},i7=function(a){g.X.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.oma()]},{D:"div",K:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.api=a;this.i=new g.NL(this,250);g.I(this,this.i);this.N(a,"presentingplayerstatechange",this.l);BKa(this,a.Xa())},BKa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.W(b,128)?g.CJ("Error on $RECEIVER_NAME",c):b.Nb()||g.W(b,4)?g.CJ("Playing on $RECEIVER_NAME",c):g.CJ("Connected to $RECEIVER_NAME",c);a.Aa("statustext",c);a.i.show()}else a.i.hide()},j7=function(a,b){g.SP.call(this,"Play on",0,a,b);
this.G=a;this.Nl={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},k7=function(a){g.hN.call(this,a);
this.di={key:v4(),name:"This computer"};this.lh=null;this.subscriptions=[];this.Ez=this.xb=null;this.Nl=[this.di];this.Yk=this.di;this.Rc=new g.dK(64);this.zE=0;this.Me=-1;this.Uo=null;this.Lr=this.pu=!1;this.Bn=this.jp=null;if(!g.ZF(this.player.T())){a=this.player;var b=g.NM(a);b&&(b=b.fn())&&(b=new j7(a,b),g.I(this,b));b=new i7(a);g.I(this,b);g.XM(a,b.element,4);this.jp=new h7;g.I(this,this.jp);g.XM(a,this.jp.element,4);g.U(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.U(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.Uo=new g7,g.I(this,this.Uo),g.XM(a,this.Uo.element,4));this.Lr=!!R6();this.pu=!!g.Hu("yt-remote-manual-pairing-warning-shown")}},l7=function(a){a.Bn&&(a.player.removeEventListener("presentingplayerstatechange",a.Bn),a.Bn=null)},CKa=function(a,b,c){a.Rc=c;
a.player.V("presentingplayerstatechange",new g.iJ(c,b))},DKa=function(a,b,c){var d=!1;
1===b?d=!a.Lr:2===b&&(d=!a.pu);d&&g.kJ(c,8)&&(a.player.pauseVideo(),l7(a))},m7=function(a,b){if(b.key!==a.Yk.key)if(b.key===a.di.key)X6();
else{if(a.Uo&&!a.pu&&b!==a.di&&"cast-selector-receiver"!==b.key&&g.sG(a.player.T()))EKa(a);else{var c;(c=!g.U(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.P("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.P("SESSION_INDEX")&&!g.P("LOGGED_IN")))||a.Lr||!a.jp);(c?0:g.sG(a.player.T())||g.wG(a.player.T()))&&FKa(a)}a.Yk=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.U(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.Na(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.ga,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=LHa(c))&&(d.locationInfo=c);c=d}O6("Connecting to: "+g.yj(b));"cast-selector-receiver"==b.key?(Q6(c||null),c=c||null,
j6()?g6().setLaunchParams(c):e6("setLaunchParams called before ready.")):!c&&$6()&&N6()==b.key?p4("yt-remote-connection-change",!0):(X6(),Q6(c||null),c=M6().Lg(),(c=x4(c,b.key))&&Y6(c,1))}},FKa=function(a){a.player.Xa().Nb()?a.player.pauseVideo():(a.Bn=function(b){DKa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Bn));
a.jp&&a.jp.Fc();U6()||(b7=!0)},EKa=function(a){a.player.Xa().Nb()?a.player.pauseVideo():(a.Bn=function(b){DKa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Bn));
a.Uo&&a.Uo.Fc();U6()||(b7=!0)},AIa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},Y4={"'":"\\'"},GKa={},UHa={WR:"atp",m1:"ska",h0:"que",zZ:"mus",l1:"sus",PV:"dsp",A0:"seq",dZ:"mic",PU:"dpa",iS:"cds"},D4,z4="",nIa=iIa("loadCastFramework")||iIa("loadCastApplicationFramework"),pIa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(I4,g.E);g.k=I4.prototype;g.k.og=function(a){this.B=arguments;this.i=!1;this.ib?this.u=g.Ta()+this.Jf:this.ib=g.Bm(this.C,this.Jf)};
g.k.stop=function(){this.ib&&(g.A.clearTimeout(this.ib),this.ib=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.I.apply(null,this.B)))};
g.k.da=function(){this.stop();I4.Fd.da.call(this)};
g.k.QJ=function(){this.u?(this.ib=g.Bm(this.C,this.u-g.Ta()),this.u=null):(this.ib=null,this.l?this.i=!0:(this.i=!1,this.I.apply(null,this.B)))};g.u(J4,g.E);g.k=J4.prototype;g.k.og=function(a){this.u=arguments;this.ib||this.l?this.i=!0:K4(this)};
g.k.stop=function(){this.ib&&(g.A.clearTimeout(this.ib),this.ib=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.ib||(this.i=!1,K4(this))};
g.k.da=function(){g.E.prototype.da.call(this);this.stop()};M4.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
M4.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var O4=new g.Rl;g.u(rIa,g.xl);Q4.prototype.i=null;Q4.prototype.getOptions=function(){var a;(a=this.i)||(a={},tIa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var n7;g.Ua(sIa,Q4);n7=new sIa;g.k=R4.prototype;g.k.im=null;g.k.Ai=!1;g.k.Fp=null;g.k.OA=null;g.k.lp=null;g.k.zp=null;g.k.Sk=null;g.k.Ql=null;g.k.Cn=null;g.k.Be=null;g.k.Es=0;g.k.Ei=null;g.k.Gv=null;g.k.Mk=null;g.k.aq=-1;g.k.TG=!0;g.k.Lm=!1;g.k.xw=0;g.k.Su=null;var yIa={},U4={};g.k=R4.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.ZP=function(a){a=a.target;var b=this.Su;b&&3==c5(a)?b.og():this.NH(a)};
g.k.NH=function(a){try{if(a==this.Be)a:{var b=c5(this.Be),c=this.Be.I,d=this.Be.getStatus();if(g.Be&&!g.de(10)||g.De&&!g.be("420+")){if(4>b)break a}else if(3>b||3==b&&!g.kg&&!e5(this.Be))break a;this.Lm||4!=b||7==c||(8==c||0>=d?this.i.hi(3):this.i.hi(2));Z4(this);var e=this.Be.getStatus();this.aq=e;var f=e5(this.Be);(this.Ai=200==e)?(4==b&&W4(this),this.I?(zIa(this,b,f),g.kg&&this.Ai&&3==b&&(this.B.ya(this.u,"tick",this.TP),this.u.start())):V4(this,f),this.Ai&&!this.Lm&&(4==b?this.i.Ts(this):(this.Ai=
!1,T4(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Mk=3,P4(13)):(this.Mk=0,P4(14)),W4(this),X4(this))}}catch(h){this.Be&&e5(this.Be)}finally{}};
g.k.TP=function(){var a=c5(this.Be),b=e5(this.Be);this.Es<b.length&&(Z4(this),zIa(this,a,b),this.Ai&&4!=a&&T4(this))};
g.k.wP=function(a){N4((0,g.C)(this.vP,this,a),0)};
g.k.vP=function(a){this.Lm||(Z4(this),V4(this,a),T4(this))};
g.k.cG=function(a){N4((0,g.C)(this.uP,this,a),0)};
g.k.uP=function(a){this.Lm||(W4(this),this.Ai=a,this.i.Ts(this),this.i.hi(4))};
g.k.cancel=function(){this.Lm=!0;W4(this)};
g.k.EP=function(){this.Fp=null;var a=Date.now();0<=a-this.OA?(2!=this.zp&&this.i.hi(3),W4(this),this.Mk=2,P4(18),X4(this)):CIa(this,this.OA-a)};
g.k.getLastError=function(){return this.Mk};g.Ua(a5,g.Rl);var JIa=/^https?$/i,HKa=["POST","PUT"];g.k=a5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.W+"; newUri="+a);b=b?b.toUpperCase():"GET";this.W=a;this.u="";this.I=0;this.za=b;this.ga=!1;this.B=!0;this.i=this.ea?uIa(this.ea):uIa(n7);this.ca=this.ea?this.ea.getOptions():n7.getOptions();this.i.onreadystatechange=(0,g.C)(this.QF,this);try{o4(d5(this,"Opening Xhr")),this.la=!0,this.i.open(b,String(a),!0),this.la=!1}catch(f){o4(d5(this,"Error opening Xhr: "+f.message));IIa(this,f);return}a=
c||"";var e=this.headers.clone();d&&QHa(d,function(f,h){e.set(h,f)});
d=g.cb(e.sh(),GIa);c=g.A.FormData&&a instanceof g.A.FormData;!g.fb(HKa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.Da&&(this.i.responseType=this.Da);"withCredentials"in this.i&&this.i.withCredentials!==this.ia&&(this.i.withCredentials=this.ia);try{LIa(this),0<this.J&&(this.Y=FIa(this.i),o4(d5(this,"Will abort after "+this.J+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.i.timeout=this.J,this.i.ontimeout=(0,g.C)(this.KB,this)):this.X=g.Bm(this.KB,this.J,this)),o4(d5(this,"Sending request")),this.L=!0,this.i.send(a),this.L=!1}catch(f){o4(d5(this,"Send error: "+f.message)),IIa(this,f)}};
g.k.KB=function(){"undefined"!=typeof g.F_&&this.i&&(this.u="Timed out after "+this.J+"ms, aborting",this.I=8,d5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(d5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),b5(this))};
g.k.da=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),b5(this,!0));a5.Fd.da.call(this)};
g.k.QF=function(){this.na()||(this.la||this.L||this.C?KIa(this):this.DO())};
g.k.DO=function(){KIa(this)};
g.k.isActive=function(){return!!this.i};
g.k.isComplete=function(){return 4==c5(this)};
g.k.getStatus=function(){try{return 2<c5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.isComplete())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=MIa.prototype;g.k.yw=null;g.k.Cg=null;g.k.Tu=!1;g.k.dH=null;g.k.zt=null;g.k.Sy=null;g.k.zw=null;g.k.Ma=null;g.k.Mj=-1;g.k.bq=null;g.k.mq=null;g.k.connect=function(a){this.zw=a;a=f5(this.i,null,this.zw);P4(3);this.dH=Date.now();var b=this.i.J;null!=b?(this.bq=b[0],(this.mq=b[1])?(this.Ma=1,NIa(this)):(this.Ma=2,h5(this))):(m4(a,"MODE","init"),this.Cg=new R4(this,void 0,void 0,void 0),this.Cg.im=this.yw,S4(this.Cg,a,!1,null,!0),this.Ma=0)};
g.k.GK=function(a){if(a)this.Ma=2,h5(this);else{P4(4);var b=this.i;b.Li=b.Wk.Mj;o5(b,9)}a&&this.hi(2)};
g.k.Ax=function(a){return this.i.Ax(a)};
g.k.abort=function(){this.Cg&&(this.Cg.cancel(),this.Cg=null);this.Mj=-1};
g.k.LB=function(){return!1};
g.k.TF=function(a,b){this.Mj=a.aq;if(0==this.Ma)if(b){try{var c=this.l.parse(b)}catch(d){c=this.i;c.Li=this.Mj;o5(c,2);return}this.bq=c[0];this.mq=c[1]}else c=this.i,c.Li=this.Mj,o5(c,2);else if(2==this.Ma)if(this.Tu)P4(7),this.Sy=Date.now();else if("11111"==b){if(P4(6),this.Tu=!0,this.zt=Date.now(),c=this.zt-this.dH,!g.Be||g.de(10)||500>c)this.Mj=200,this.Cg.cancel(),P4(12),g5(this.i,this,!0)}else P4(8),this.zt=this.Sy=Date.now(),this.Tu=!1};
g.k.Ts=function(){this.Mj=this.Cg.aq;if(this.Cg.Ai)0==this.Ma?this.mq?(this.Ma=1,NIa(this)):(this.Ma=2,h5(this)):2==this.Ma&&((!g.Be||g.de(10)?!this.Tu:200>this.Sy-this.zt)?(P4(11),g5(this.i,this,!1)):(P4(12),g5(this.i,this,!0)));else{0==this.Ma?P4(9):2==this.Ma&&P4(10);var a=this.i;this.Cg.getLastError();a.Li=this.Mj;o5(a,2)}};
g.k.ds=function(){return this.i.ds()};
g.k.isActive=function(){return this.i.isActive()};
g.k.hi=function(a){this.i.hi(a)};g.k=i5.prototype;g.k.Ki=null;g.k.Fq=null;g.k.pg=null;g.k.Xd=null;g.k.Aw=null;g.k.At=null;g.k.zC=null;g.k.Us=null;g.k.zr=0;g.k.vM=0;g.k.Bf=null;g.k.jl=null;g.k.Qj=null;g.k.Um=null;g.k.Wk=null;g.k.Ev=null;g.k.Po=-1;g.k.yE=-1;g.k.Li=-1;g.k.wo=0;g.k.ho=0;g.k.Mm=8;g.Ua(PIa,g.xl);g.Ua(QIa,g.xl);g.k=i5.prototype;g.k.connect=function(a,b,c,d,e){P4(0);this.Aw=b;this.Fq=c||{};d&&void 0!==e&&(this.Fq.OSID=d,this.Fq.OAID=e);this.C?(N4((0,g.C)(this.SC,this,a),100),UIa(this)):this.SC(a)};
g.k.SC=function(a){this.Wk=new MIa(this);this.Wk.yw=this.Ki;this.Wk.l=this.B;this.Wk.connect(a)};
g.k.LB=function(){return 0==this.Ma};
g.k.getState=function(){return this.Ma};
g.k.aG=function(a){this.jl=null;YIa(this,a)};
g.k.ZF=function(){this.Qj=null;this.Xd=new R4(this,this.l,"rpc",this.I);this.Xd.im=this.Ki;this.Xd.xw=0;var a=this.zC.clone();k4(a,"RID","rpc");k4(a,"SID",this.l);k4(a,"CI",this.Ev?"0":"1");k4(a,"AID",this.Po);j5(this,a);if(!g.Be||g.de(10))k4(a,"TYPE","xmlhttp"),S4(this.Xd,a,!0,this.Us,!1);else{k4(a,"TYPE","html");var b=this.Xd,c=!!this.Us;b.zp=3;b.Sk=l4(a.clone());BIa(b,c)}};
g.k.TF=function(a,b){if(0!=this.Ma&&(this.Xd==a||this.pg==a))if(this.Li=a.aq,this.pg==a&&3==this.Ma)if(7<this.Mm){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Qj){if(this.Xd)if(this.Xd.lp+3E3<this.pg.lp)l5(this),this.Xd.cancel(),this.Xd=null;else break a;n5(this);P4(19)}}else this.yE=c[1],0<this.yE-this.Po&&37500>c[2]&&this.Ev&&0==this.ho&&!this.Um&&(this.Um=N4((0,g.C)(this.ZM,this),6E3));else o5(this,11)}else b!=GKa.DU.i&&o5(this,11);else if(this.Xd==
a&&l5(this),!g.rc(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Po=e[0];e=e[1];2==this.Ma?"c"==e[0]?(this.l=e[1],this.Us=e[2],e=e[3],null!=e?this.Mm=e:this.Mm=6,this.Ma=3,this.Bf&&this.Bf.OC(),this.zC=f5(this,this.ds()?this.Us:null,this.Aw),ZIa(this)):"stop"==e[0]&&o5(this,7):3==this.Ma&&("stop"==e[0]?o5(this,7):"noop"!=e[0]&&this.Bf&&this.Bf.NC(e),this.ho=0)}}};
g.k.ZM=function(){null!=this.Um&&(this.Um=null,this.Xd.cancel(),this.Xd=null,n5(this),P4(20))};
g.k.Ts=function(a){if(this.Xd==a){l5(this);this.Xd=null;var b=2}else if(this.pg==a)this.pg=null,b=1;else return;this.Li=a.aq;if(0!=this.Ma)if(a.Ai)1==b?(b=O4,b.dispatchEvent(new PIa(b,a.Cn?a.Cn.length:0,Date.now()-a.lp,this.wo)),k5(this),this.u.length=0):ZIa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Li)){if(d=1==b)this.pg||this.jl||1==this.Ma||2<=this.wo?d=!1:(this.jl=N4((0,g.C)(this.aG,this,a),$Ia(this,this.wo)),this.wo++,d=!0);d=!(d||2==b&&n5(this))}if(d)switch(c){case 1:o5(this,
5);break;case 4:o5(this,10);break;case 3:o5(this,6);break;case 7:o5(this,12);break;default:o5(this,2)}}};
g.k.aL=function(a){if(!g.fb(arguments,this.Ma))throw Error("Unexpected channel state: "+this.Ma);};
g.k.GQ=function(a){a?P4(2):(P4(1),aJa(this,8))};
g.k.Ax=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new a5;a.ia=!1;return a};
g.k.isActive=function(){return!!this.Bf&&this.Bf.isActive(this)};
g.k.hi=function(a){var b=O4;b.dispatchEvent(new QIa(b,a))};
g.k.ds=function(){return!(!g.Be||g.de(10))};
g.k=bJa.prototype;g.k.OC=function(){};
g.k.NC=function(){};
g.k.MC=function(){};
g.k.jx=function(){};
g.k.xD=function(){return{}};
g.k.isActive=function(){return!0};g.k=cJa.prototype;g.k.isEmpty=function(){return g.gb(this.i)&&g.gb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.fb(this.i,a)||g.fb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.FCa)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.l,a)};
g.k.sg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Ua(p5,g.E);g.k=p5.prototype;g.k.oP=function(){this.Jf=Math.min(3E5,2*this.Jf);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Jf+15E3*Math.random();g.$m(this.i,a);this.l=g.Ta()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Jf=5E3};g.Ua(q5,bJa);g.k=q5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Pf=function(a){return this.u.Pf(a)};
g.k.V=function(a,b){return this.u.V.apply(this.u,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.zi(this.u),fJa(this),g.zi(this.l),this.l=null,this.Y=function(){return""})};
g.k.na=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.W="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ca+"/test";b=this.ca+"/bind";var d=new i5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ea),e=this.i;e&&(e.Bf=null);d.Bf=this;this.i=d;r5(this);if(this.i){d=g.P("ID_TOKEN");var f=this.i.Ki||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Ki=f}e?(3!=e.getState()&&0==WIa(e)||e.getState(),this.i.connect(a,b,this.I,e.l,e.Po)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Yb(c,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(c):s5(this)&&(r5(this),VIa(this.i,c))};
g.k.OC=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)VIa(this.i,a[b])}this.V("handlerOpened")};
g.k.MC=function(a){var b=2==a&&401==this.i.Li;4==a||b||this.l.start();this.V("handlerError",a,b)};
g.k.jx=function(a){if(!this.l.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.xD=function(){var a={v:2};this.W&&(a.gsessionid=this.W);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Yb(a,this.C);return a};
g.k.NC=function(a){"S"==a[0]?this.W=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),TIa(this.i)):this.V("handlerMessage",new dJa(a[0],a[1]))};
g.k.dv=function(a){(this.I.loungeIdToken=a)||this.l.stop();if(this.ia&&this.i){var b=this.i.Ki||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Ki=b}};
g.k.jQ=function(){this.l.isActive();0==WIa(this.i)&&this.connect(this.C,this.B)};t5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
t5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
t5.prototype.C=function(a){a(Error("request timed out"))};var mJa=Date.now(),w5=null,z5=Array(50),y5=-1,A5=!1;g.Ua(B5,g.R);B5.prototype.Lg=function(){return this.screens};
B5.prototype.contains=function(a){return!!w4(this.screens,a)};
B5.prototype.get=function(a){return a?x4(this.screens,a):null};
B5.prototype.info=function(a){x5(this.I,a)};g.u(C5,g.R);g.k=C5.prototype;g.k.start=function(){!this.i&&isNaN(this.ib)&&this.mG()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.ib)||(g.so(this.ib),this.ib=NaN)};
g.k.da=function(){this.stop();g.R.prototype.da.call(this)};
g.k.mG=function(){this.ib=NaN;this.i=g.Pp(u5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.C)(this.SJ,this),onError:(0,g.C)(this.RJ,this),onTimeout:(0,g.C)(this.TJ,this)})};
g.k.SJ=function(a,b){this.i=null;var c=b.screen||{};c.dialId=this.B;c.name=this.I;var d=-1;this.C&&c.shortLivedLoungeToken&&c.shortLivedLoungeToken.value&&c.shortLivedLoungeToken.refreshIntervalMs&&(c.screenIdType="shortLived",c.loungeToken=c.shortLivedLoungeToken.value,d=c.shortLivedLoungeToken.refreshIntervalMs);this.V("pairingComplete",new r4(c),d)};
g.k.RJ=function(a){this.i=null;a.status&&404==a.status?this.l>=IKa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=IKa[this.l],this.ib=g.qo((0,g.C)(this.mG,this),a),this.l++):this.V("pairingFailed",Error("Server error "+a.status))};
g.k.TJ=function(){this.i=null;this.V("pairingFailed",Error("Server not responding"))};
var IKa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(E5,B5);g.k=E5.prototype;g.k.start=function(){D5(this)&&this.V("screenChange");!g.Hu("yt-remote-lounge-token-expiration")&&qJa(this);g.so(this.i);this.i=g.qo((0,g.C)(this.start,this),1E4)};
g.k.add=function(a,b){D5(this);nJa(this,a);F5(this,!1);this.V("screenChange");b(a);a.token||qJa(this)};
g.k.remove=function(a,b){var c=D5(this);pJa(this,a)&&(F5(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.k.Cv=function(a,b,c,d){var e=D5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,F5(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.k.da=function(){g.so(this.i);E5.Fd.da.call(this)};
g.k.yL=function(a){D5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}F5(this,!b);b&&x5(this.I,"Missed "+b+" lounge tokens.")};
g.k.xL=function(a){x5(this.I,"Requesting lounge tokens failed: "+a)};g.u(H5,g.R);g.k=H5.prototype;g.k.start=function(){var a=parseInt(g.Hu("yt-remote-fast-check-period")||"0",10);(this.B=g.Ta()-144E5<a?0:a)?K5(this):(this.B=g.Ta()+3E5,g.Gu("yt-remote-fast-check-period",this.B),this.Oz())};
g.k.isEmpty=function(){return g.Pb(this.i)};
g.k.update=function(){G5("Updating availability on schedule.");var a=this.I(),b=g.Db(this.i,function(c,d){return c&&!!x4(a,d)},this);
J5(this,b)};
g.k.da=function(){g.so(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.R.prototype.da.call(this)};
g.k.Oz=function(){g.so(this.u);this.u=NaN;this.l&&this.l.abort();var a=sJa(this);if(n4(a)){var b=u5(this.C,"/pairing/get_screen_availability");this.l=v5(this.C,b,{lounge_token:g.Kb(a).join(",")},(0,g.C)(this.XO,this,a),(0,g.C)(this.WO,this))}else J5(this,{}),K5(this)};
g.k.XO=function(a,b){this.l=null;var c=g.Kb(sJa(this));if(g.yb(c,g.Kb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;J5(this,d);K5(this)}else this.Gd("Changing Screen set during request."),this.Oz()};
g.k.WO=function(a){this.Gd("Screen availability failed: "+a);this.l=null;K5(this)};
g.k.Gd=function(a){x5("OnlineScreenService",a)};g.Ua(L5,B5);g.k=L5.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.V("screenChange"),this.i.isEmpty()||this.V("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Cv=function(a,b,c,d){this.l.contains(a)?this.l.Cv(a,b,c,d):(a="Updating name of unknown screen: "+a.name,x5(this.I,a),d(Error(a)))};
g.k.Lg=function(a){return a?this.screens:g.nb(this.screens,g.Ne(this.u,function(b){return!this.contains(b)},this))};
g.k.MB=function(){return g.Ne(this.Lg(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.NB=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new C5(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.zi(l);e(M5(h,m),n)});
l.subscribe("pairingFailed",function(m){g.zi(l);f(m)});
l.start();return(0,g.C)(l.stop,l)};
g.k.UJ=function(a,b,c,d){g.Pp(u5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.C)(function(e,f){var h=new r4(f.screen||{});if(!h.name||wJa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);wJa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(M5(this,h))},this),
onError:(0,g.C)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.C)(function(){d(Error("pairing request timed out."))},this)})};
g.k.da=function(){g.zi(this.l);g.zi(this.i);L5.Fd.da.call(this)};
g.k.EL=function(){yJa(this);this.V("screenChange");this.i.update()};
L5.prototype.dispose=L5.prototype.dispose;g.Ua(O5,g.R);g.k=O5.prototype;g.k.getScreen=function(){return this.B};
g.k.cg=function(a){this.na()||(a&&Q5(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.k.info=function(a){x5(this.ia,a)};
g.k.OB=function(){return null};
g.k.Zz=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.C)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.C)(function(){Q5(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.da=function(){this.Zz("");O5.Fd.da.call(this)};g.u(R5,O5);g.k=R5.prototype;g.k.Yz=function(a){if(this.l){if(this.l==a)return;Q5(this,"Overriding cast session with new session object");HJa(this);this.ca=!1;this.W="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ea)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ea);DJa(this,"getMdxSessionStatus")};
g.k.Qo=function(a){this.info("launchWithParams no-op for Cast: "+g.yj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.C)(function(){this.cg()},this),(0,g.C)(function(){this.cg(Error("Failed to stop receiver app."))},this)):this.cg(Error("Stopping cast device without session."))};
g.k.Zz=function(){};
g.k.da=function(){this.info("disposeInternal");HJa(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ea));this.l=null;O5.prototype.da.call(this)};
g.k.IP=function(a,b){if(!this.na())if(b){var c=L4(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.yj(c));switch(d){case "mdxSessionStatus":BJa(this,c);break;case "loungeToken":EJa(this,c);break;default:Q5(this,"Unknown youtube message: "+d)}}else Q5(this,"Unable to parse message.")}else Q5(this,"No data in message.")};
g.k.MD=function(a,b,c,d){g.so(this.L);this.L=0;vJa(this.u,this.i.label,a,this.i.friendlyName,(0,g.C)(function(e){e?b(e):0<=d?(Q5(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.qo((0,g.C)(this.MD,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.OB=function(){return this.l};
g.k.VJ=function(a){this.na()||a||(Q5(this,"Cast session died."),this.cg())};g.u(U5,O5);g.k=U5.prototype;g.k.Yz=function(a){this.l=a;this.l.addUpdateListener(this.ga)};
g.k.Qo=function(a){this.la=a;this.X()};
g.k.stop=function(){OJa(this);this.l?this.l.stop((0,g.C)(this.cg,this,null),(0,g.C)(this.cg,this,"Failed to stop DIAL device.")):this.cg()};
g.k.da=function(){OJa(this);this.l&&this.l.removeUpdateListener(this.ga);this.l=null;O5.prototype.da.call(this)};
g.k.WJ=function(a){this.na()||a||(Q5(this,"DIAL session died."),this.C(),this.C=g.Ka,this.cg())};g.u(Y5,O5);Y5.prototype.stop=function(){this.cg()};
Y5.prototype.Yz=function(){};
Y5.prototype.Qo=function(){g.so(this.l);this.l=NaN;var a=x4(this.u.Lg(),this.i.label);a?P5(this,a):this.cg(Error("No such screen"))};
Y5.prototype.da=function(){g.so(this.l);this.l=NaN;O5.prototype.da.call(this)};g.u(Z5,g.R);g.k=Z5.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.W||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.C)(this.HO,this);c=new chrome.cast.ApiConfig(c,(0,g.C)(this.VF,this),f,d,e);c.customDialLaunchCallback=(0,g.C)(this.uN,this);chrome.cast.initialize(c,(0,g.C)(function(){this.na()||
(chrome.cast.addReceiverActionListener(this.I),jJa(),this.l.subscribe("onlineScreenChange",(0,g.C)(this.PB,this)),this.u=QJa(this),chrome.cast.setCustomReceivers(this.u,g.Ka,(0,g.C)(function(h){this.Gd("Failed to set initial custom receivers: "+g.yj(h))},this)),this.V("yt-remote-cast2-availability-change",a6(this)),b(!0))},this),(0,g.C)(function(h){this.Gd("Failed to initialize API: "+g.yj(h));
b(!1)},this))};
g.k.pQ=function(a,b){$5("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)$5("Unsetting old screen status: "+this.i.i.friendlyName),b6(this,null)}if(a&&b){if(!this.i){c=x4(this.l.Lg(),a);if(!c){$5("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){$5("setConnectedScreenStatus: Screen with id type to be short lived.");return}var d=PJa(this,c);d||($5("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(d),chrome.cast.setCustomReceivers(this.u,g.Ka,(0,g.C)(function(e){this.Gd("Failed to set initial custom receivers: "+g.yj(e))},this)));
$5("setConnectedScreenStatus: new active receiver: "+d.friendlyName);b6(this,new Y5(this.l,d),!0)}this.i.Zz(b)}else $5("setConnectedScreenStatus: no screen.")};
g.k.qQ=function(a){this.na()?this.Gd("Setting connection data on disposed cast v2"):this.i?this.i.Qo(a):this.Gd("Setting connection data without a session")};
g.k.YJ=function(){this.na()?this.Gd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),b6(this,null)):$5("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.C)(this.VF,this),(0,g.C)(this.aP,this))};
g.k.da=function(){this.l.unsubscribe("onlineScreenChange",(0,g.C)(this.PB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.I);var a=gJa,b=g.Ja("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.zi(this.i);g.R.prototype.da.call(this)};
g.k.Gd=function(a){x5("Controller",a)};
g.k.XF=function(a,b){this.i==a&&(b||b6(this,null),this.V("yt-remote-cast2-session-change",b))};
g.k.EO=function(a,b){if(!this.na())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),$5("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)$5("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{$5("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.V("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:b6(this,
new Y5(this.l,a));break;case chrome.cast.ReceiverType.DIAL:b6(this,new U5(this.l,a,this.C,this.B));break;case chrome.cast.ReceiverType.CAST:b6(this,new R5(this.l,a,this.B));break;default:this.Gd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Gd("Stopping receiver w/o session: "+a.friendlyName)}else this.Gd("onReceiverAction_ called without receiver.")};
g.k.uN=function(a){if(this.na())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Gd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Gd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return $5("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Gd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);b6(this,new U5(this.l,b,this.C,this.B))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,V5(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=LJa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.no(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=MJa(b,c)):a=MJa(b,c)):a=X5(b);return a};
g.k.VF=function(a){if(!this.na()){$5("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)$5("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),b6(this,new R5(this.l,b,this.B),!0);else{this.Gd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=x4(this.l.Lg(),c.label);d&&s4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&($5("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.zi(this.i),this.i=new R5(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.C)(this.XF,this,this.i)),this.i.Qo(null));this.i.Yz(a)}}};
g.k.XJ=function(){return this.i?this.i.OB():null};
g.k.aP=function(a){this.na()||(this.Gd("Failed to estabilish a session: "+g.yj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&b6(this,null))};
g.k.HO=function(a){$5("Receiver availability updated: "+a);if(!this.na()){var b=a6(this);this.J=a==chrome.cast.ReceiverAvailability.AVAILABLE;a6(this)!=b&&this.V("yt-remote-cast2-availability-change",a6(this))}};
g.k.PB=function(){this.na()||(this.u=QJa(this),$5("Updating custom receivers: "+g.yj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ka,(0,g.C)(function(){this.Gd("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",a6(this)))};
Z5.prototype.setLaunchParams=Z5.prototype.qQ;Z5.prototype.setConnectedScreenStatus=Z5.prototype.pQ;Z5.prototype.stopSession=Z5.prototype.YJ;Z5.prototype.getCastSession=Z5.prototype.XJ;Z5.prototype.requestSession=Z5.prototype.requestSession;Z5.prototype.init=Z5.prototype.init;Z5.prototype.dispose=Z5.prototype.dispose;var h6=[];g.k=m6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";n6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.i=a.trackData,this.aj=a.hasPrevious,this.hasNext=a.hasNext,this.L=a.playerTime,this.J=a.playerTimeAt,this.C=a.seekableStart,this.l=a.seekableEnd,this.I=a.duration,this.W=a.loadedTime,this.B=a.liveIngestionTime,this.u=!isNaN(this.B))};
g.k.Nb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.u?this.I+o6(this):this.I};
g.k.clone=function(){return new m6(s6(this))};g.u(u6,g.R);g.k=u6.prototype;g.k.getState=function(){return this.Ma};
g.k.play=function(){w6(this)?(this.i?this.i.play(null,g.Ka,B6(this,"play")):A6(this,"play"),z6(this,1,q6(v6(this))),this.V("remotePlayerChange")):x6(this,this.play)};
g.k.pause=function(){w6(this)?(this.i?this.i.pause(null,g.Ka,B6(this,"pause")):A6(this,"pause"),z6(this,2,q6(v6(this))),this.V("remotePlayerChange")):x6(this,this.pause)};
g.k.seekTo=function(a){if(w6(this)){if(this.i){var b=v6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Nb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ka,B6(this,"seekTo",{newTime:a}))}else A6(this,"seekTo",{newTime:a});z6(this,3,a);this.V("remotePlayerChange")}else x6(this,g.Ra(this.seekTo,a))};
g.k.stop=function(){if(w6(this)){this.i?this.i.stop(null,g.Ka,B6(this,"stopVideo")):A6(this,"stopVideo");var a=v6(this);a.index=-1;a.videoId="";n6(a);y6(this,a);this.V("remotePlayerChange")}else x6(this,this.stop)};
g.k.setVolume=function(a,b){if(w6(this)){var c=v6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.C)(function(){x5("CP","set receiver volume: "+d)},this),(0,g.C)(function(){this.Gd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.C)(function(){x5("CP","set receiver muted: "+b)},this),(0,g.C)(function(){this.Gd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);A6(this,"setVolume",e)}c.muted=b;c.volume=a;y6(this,c)}else x6(this,g.Ra(this.setVolume,a,b))};
g.k.QB=function(a,b){if(w6(this)){var c=v6(this),d={videoId:a};b&&(c.i={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.yj(b.style),g.Yb(d,c.i));A6(this,"setSubtitlesTrack",d);y6(this,c)}else x6(this,g.Ra(this.QB,a,b))};
g.k.setAudioTrack=function(a,b){if(w6(this)){var c=b.getLanguageInfo().getId();A6(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=v6(this);d.audioTrackId=c;y6(this,d)}else x6(this,g.Ra(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=v6(this);c=c||0;var m={videoId:a,currentIndex:c};r6(l,a,c);void 0!==b&&(p6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.yj(h));A6(this,"setPlaylist",m);d||y6(this,l)};
g.k.Ou=function(a,b){if(w6(this)){if(a&&b){var c=v6(this);r6(c,a,b);y6(this,c)}A6(this,"previous")}else x6(this,g.Ra(this.Ou,a,b))};
g.k.nextVideo=function(a,b){if(w6(this)){if(a&&b){var c=v6(this);r6(c,a,b);y6(this,c)}A6(this,"next")}else x6(this,g.Ra(this.nextVideo,a,b))};
g.k.gD=function(){w6(this)?A6(this,"dismissAutoplay"):x6(this,this.gD)};
g.k.dispose=function(){if(3!=this.Ma){var a=this.Ma;this.Ma=3;this.V("proxyStateChange",a,this.Ma)}g.R.prototype.dispose.call(this)};
g.k.da=function(){bKa(this);this.u=null;this.B.clear();t6(this,null);g.R.prototype.da.call(this)};
g.k.cA=function(a){if((a!=this.Ma||2==a)&&3!=this.Ma&&0!=a){var b=this.Ma;this.Ma=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.gb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.BO=function(a,b){this.V(a,b)};
g.k.gN=function(a){if(!a)this.Cr(null),t6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=v6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)x5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,y6(this,b)}};
g.k.Cr=function(a){x5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),cKa(this),this.V("remotePlayerChange")};
g.k.fN=function(a){a?(cKa(this),this.V("remotePlayerChange")):this.Cr(null)};
g.k.tA=function(){A6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.nN=function(){var a=ZJa();a&&t6(this,a)};
g.k.Gd=function(a){x5("CP",a)};g.u(C6,g.R);g.k=C6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Hb.listId=c);this.Hb.videoId=d;this.Hb.index=h||0;this.Hb.state=3;p6(this.Hb,m);this.B="UNSUPPORTED";D6("Connecting with setPlaylist and params: "+g.yj(l));this.i.connect({method:"setPlaylist",
params:g.yj(l)},a,bIa())}else D6("Connecting without params"),this.i.connect({},a,bIa());eKa(this)};
g.k.dv=function(a){this.i.dv(a)};
g.k.dispose=function(){this.na()||(this.V("beforeDispose"),E6(this,3));g.R.prototype.dispose.call(this)};
g.k.da=function(){F6(this);H6(this);G6(this);g.so(this.J);this.J=NaN;g.so(this.L);this.L=NaN;this.u=null;g.To(this.W);this.W.length=0;this.i.dispose();g.R.prototype.da.call(this);this.B=this.I=this.l=this.Hb=this.i=null};
g.k.sL=function(){this.ro(2)};
g.k.kN=function(){D6("Channel opened");this.ca&&(this.ca=!1,G6(this),this.Y=g.qo((0,g.C)(function(){D6("Timing out waiting for a screen.");this.ro(1)},this),15E3));
fIa(eJa(this.i),this.ga)};
g.k.hN=function(){D6("Channel closed");isNaN(this.C)?C4(!0):C4();this.dispose()};
g.k.iN=function(a,b){C4();isNaN(this.Wq())?(b&&"shortLived"==this.ea&&this.V("browserChannelAuthError",a),D6("Channel error: "+a+" without reconnection"),this.dispose()):(this.ca=!0,D6("Channel error: "+a+" with reconnection in "+this.Wq()+" ms"),E6(this,2))};
g.k.jN=function(a){a.params?D6("Received: action="+a.action+", params="+g.yj(a.params)):D6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=L4(a.params.devices);this.l=g.Qc(a,function(c){return new q4(c)});
a=!!g.cb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
hKa(this,a);break;case "loungeScreenDisconnected":g.lb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
hKa(this,!1);break;case "remoteConnected":var b=new q4(L4(a.params.device));g.cb(this.l,function(c){return b?c.id==b.id:!1})||MHa(this.l,b);
break;case "remoteDisconnected":b=new q4(L4(a.params.device));g.lb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":jKa(this,a);break;case "nowPlaying":lKa(this,a);break;case "onStateChange":kKa(this,a);break;case "onAdStateChange":mKa(this,a);break;case "onVolumeChanged":nKa(this,a);break;case "onSubtitlesTrackChanged":iKa(this,a);break;case "nowAutoplaying":oKa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.V("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.V("autoplayModeChange",this.B);"DISABLED"==this.B&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":pKa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:D6("Unrecognized action: "+a.action)}};
g.k.fQ=function(){if(this.u){var a=this.u;this.u=null;this.Hb.videoId!=a&&I6(this,"getNowPlaying")}};
g.k.oL=function(){var a=3;this.na()||(a=0,isNaN(this.Wq())?s5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.ro=function(a){D6("Disconnecting with "+a);F6(this);this.V("beforeDisconnect",a);1==a&&C4();fJa(this.i,a);this.dispose()};
g.k.mL=function(){var a=this.Hb;this.u&&(a=this.Hb.clone(),r6(a,this.u,a.index));return s6(a)};
g.k.rQ=function(a){var b=new m6(a);b.videoId&&b.videoId!=this.Hb.videoId&&(this.u=b.videoId,g.so(this.J),this.J=g.qo((0,g.C)(this.fQ,this),5E3));var c=[];this.Hb.listId==b.listId&&this.Hb.videoId==b.videoId&&this.Hb.index==b.index||c.push("remoteQueueChange");this.Hb.playerState==b.playerState&&this.Hb.volume==b.volume&&this.Hb.muted==b.muted&&q6(this.Hb)==q6(b)&&g.yj(this.Hb.i)==g.yj(b.i)||c.push("remotePlayerChange");this.Hb.reset(a);g.Ab(c,function(d){this.V(d)},this)};
g.k.LD=function(){var a=this.i.I.id,b=g.cb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Wq=function(){var a=this.i;return a.l.isActive()?a.l.l-g.Ta():NaN};
g.k.jL=function(){return this.B||"UNSUPPORTED"};
g.k.kL=function(){return this.I||""};
g.k.ZJ=function(){if(!isNaN(this.Wq())){var a=this.i.l;a.i.og();a.start()}};
g.k.oQ=function(a,b){I6(this,a,b);gKa(this)};
g.k.RB=function(){var a=g.Lq("SID","")||"",b=g.Lq("SAPISID","")||"",c=g.Lq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.sf(g.Xe(a),2);b=g.sf(g.Xe(b),2);c=g.sf(g.Xe(c),2);return g.sf(g.Xe(a+","+b+","+c),2)};
C6.prototype.subscribe=C6.prototype.subscribe;C6.prototype.unsubscribeByKey=C6.prototype.Pf;C6.prototype.getProxyState=C6.prototype.oL;C6.prototype.disconnect=C6.prototype.ro;C6.prototype.getPlayerContextData=C6.prototype.mL;C6.prototype.setPlayerContextData=C6.prototype.rQ;C6.prototype.getOtherConnectedRemoteId=C6.prototype.LD;C6.prototype.getReconnectTimeout=C6.prototype.Wq;C6.prototype.getAutoplayMode=C6.prototype.jL;C6.prototype.getAutoplayVideoId=C6.prototype.kL;C6.prototype.reconnect=C6.prototype.ZJ;
C6.prototype.sendMessage=C6.prototype.oQ;C6.prototype.getXsrfToken=C6.prototype.RB;g.u(J6,B5);g.k=J6.prototype;g.k.Lg=function(a){return this.If.$_gs(a)};
g.k.contains=function(a){return!!this.If.$_c(a)};
g.k.get=function(a){return this.If.$_g(a)};
g.k.start=function(){this.If.$_st()};
g.k.add=function(a,b,c){this.If.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.If.$_r(a,b,c)};
g.k.Cv=function(a,b,c,d){this.If.$_un(a,b,c,d)};
g.k.da=function(){for(var a=0,b=this.i.length;a<b;++a)this.If.$_ubk(this.i[a]);this.i.length=0;this.If=null;B5.prototype.da.call(this)};
g.k.aK=function(){this.V("screenChange")};
g.k.iO=function(){this.V("onlineScreenChange")};
L5.prototype.$_st=L5.prototype.start;L5.prototype.$_gspc=L5.prototype.UJ;L5.prototype.$_gsppc=L5.prototype.NB;L5.prototype.$_c=L5.prototype.contains;L5.prototype.$_g=L5.prototype.get;L5.prototype.$_a=L5.prototype.add;L5.prototype.$_un=L5.prototype.Cv;L5.prototype.$_r=L5.prototype.remove;L5.prototype.$_gs=L5.prototype.Lg;L5.prototype.$_gos=L5.prototype.MB;L5.prototype.$_s=L5.prototype.subscribe;L5.prototype.$_ubk=L5.prototype.Pf;var W6=null,b7=!1,K6=null,L6=null,a7=null,P6=[];g.u(c7,g.E);g.k=c7.prototype;g.k.da=function(){g.E.prototype.da.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.xb;a.unsubscribe("proxyStateChange",this.SF,this);a.unsubscribe("remotePlayerChange",this.Ir,this);a.unsubscribe("remoteQueueChange",this.Mu,this);a.unsubscribe("previousNextChange",this.PF,this);a.unsubscribe("nowAutoplaying",this.JF,this);a.unsubscribe("autoplayDismissed",this.hF,this);this.xb=this.l=null};
g.k.SB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.xb.Ma)if(d7(this)){if(!v6(this.xb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":v6(this.xb).Nb()?this.xb.pause():this.xb.play();break;case "control_play":this.xb.play();break;case "control_pause":this.xb.pause();break;case "control_seek":this.J.og(c[0],c[1]);break;case "control_subtitles_set_track":e7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.G.getCurrentTime();f7(this,0===c?void 0:c);break;case "control_seek":f7(this,c[0]);break;case "control_subtitles_set_track":e7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.dN=function(a){this.L.og(a)};
g.k.XQ=function(a){this.SB("control_subtitles_set_track",g.Pb(a)?null:a)};
g.k.hH=function(){var a=this.G.getOption("captions","track");g.Pb(a)||e7(this,a)};
g.k.Db=function(a){this.l.Db(a,this.G.getVideoData().lengthSeconds)};
g.k.RN=function(){g.Pb(this.B)||AKa(this,this.B);this.C=!1};
g.k.SF=function(a,b){this.u.stop();2===b&&this.cH()};
g.k.Ir=function(){if(d7(this)){this.i.stop();var a=v6(this.xb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Me=1;break;case 1082:case 1083:this.l.Me=0;break;default:this.l.Me=-1}switch(a.playerState){case 1081:case 1:this.ub(new g.dK(8));this.bH();break;case 1085:case 3:this.ub(new g.dK(9));break;case 1083:case 0:this.ub(new g.dK(2));this.J.stop();this.Db(this.G.getVideoData().lengthSeconds);break;case 1084:this.ub(new g.dK(4));break;case 2:this.ub(new g.dK(4));this.Db(q6(a));
break;case -1:this.ub(new g.dK(64));break;case -1E3:this.ub(new g.dK(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=v6(this.xb).i;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,AKa(this,a));a=v6(this.xb);-1===a.volume||Math.round(this.G.getVolume())===a.volume&&this.G.isMuted()===a.muted||this.W.isActive()||this.EH()}else zKa(this)};
g.k.PF=function(){this.G.V("mdxpreviousnextchange")};
g.k.Mu=function(){d7(this)||zKa(this)};
g.k.JF=function(a){isNaN(a)||this.G.V("mdxnowautoplaying",a)};
g.k.hF=function(){this.G.V("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){d7(this)&&this.xb.setAudioTrack(this.G.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===v6(this.xb).playerState?f7(this,a):b&&this.xb.seekTo(a)};
g.k.EH=function(){var a=this;if(d7(this)){var b=v6(this.xb);this.events.Ib(this.X);b.muted?this.G.mute():this.G.unMute();this.G.setVolume(b.volume);this.X=this.events.N(this.G,"onVolumeChange",function(c){yKa(a,c)})}};
g.k.bH=function(){this.i.stop();if(!this.xb.na()){var a=v6(this.xb);a.Nb()&&this.ub(new g.dK(8));this.Db(q6(a));this.i.start()}};
g.k.cH=function(){this.u.stop();this.i.stop();var a=this.xb.u.getReconnectTimeout();2==this.xb.Ma&&!isNaN(a)&&this.u.start()};
g.k.ub=function(a){this.u.stop();var b=this.I;if(!g.iK(b,a)){var c=g.W(a,2);c!==g.W(this.I,2)&&this.G.En(c);this.I=a;CKa(this.l,b,a)}};g.u(g7,g.X);g7.prototype.Fc=function(){this.i.show()};
g7.prototype.kb=function(){this.i.hide()};
g7.prototype.l=function(){g.KJ("https://support.google.com/youtube/answer/7640706")};
g7.prototype.u=function(){p4("mdx-manual-pairing-popup-ok");this.kb()};g.u(h7,g.X);h7.prototype.Fc=function(){this.i.show()};
h7.prototype.kb=function(){this.i.hide()};
h7.prototype.l=function(){p4("mdx-privacy-popup-cancel");this.kb()};
h7.prototype.u=function(){p4("mdx-privacy-popup-confirm");this.kb()};g.u(i7,g.X);i7.prototype.l=function(a){BKa(this,a.state)};g.u(j7,g.SP);j7.prototype.C=function(){var a=this.G.getOption("remote","receivers");a&&1<a.length&&!this.G.getOption("remote","quickCast")?(this.Nl=g.Bb(a,this.i,this),g.TP(this,g.Qc(a,this.i)),a=this.G.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.dh(a),this.enable(!0)):this.enable(!1)};
j7.prototype.i=function(a){return a.key};
j7.prototype.Oh=function(a){return"cast-selector-receiver"===a?"Cast...":this.Nl[a].name};
j7.prototype.We=function(a){g.SP.prototype.We.call(this,a);this.G.setOption("remote","currentReceiver",this.Nl[a]);this.eb.kb()};g.u(k7,g.hN);g.k=k7.prototype;
g.k.create=function(){var a=this.player.T(),b=g.XF(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.U(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.U(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.U(a.experiments,"enable_cast_short_lived_lounge_token")};tKa(b,a);this.subscriptions.push(g.xo("yt-remote-before-disconnect",this.bN,this));this.subscriptions.push(g.xo("yt-remote-connection-change",this.IO,this));this.subscriptions.push(g.xo("yt-remote-receiver-availability-change",
this.RF,this));this.subscriptions.push(g.xo("yt-remote-auto-connect",this.GO,this));this.subscriptions.push(g.xo("yt-remote-receiver-resumed",this.FO,this));this.subscriptions.push(g.xo("mdx-privacy-popup-confirm",this.WP,this));this.subscriptions.push(g.xo("mdx-privacy-popup-cancel",this.VP,this));this.subscriptions.push(g.xo("mdx-manual-pairing-popup-ok",this.kM,this));this.RF()};
g.k.load=function(){this.player.cancelPlayback();g.hN.prototype.load.call(this);this.lh=new c7(this,this.player,this.xb);var a=(a=xKa())?a.currentTime:0;var b=$6()?new u6(U6(),void 0):null;0==a&&b&&(a=q6(v6(b)));0!==a&&this.Db(a);CKa(this,this.Rc,this.Rc);this.player.xj(6)};
g.k.unload=function(){this.player.V("mdxautoplaycanceled");this.Yk=this.di;g.Ai(this.lh,this.xb);this.xb=this.lh=null;g.hN.prototype.unload.call(this);this.player.xj(5);l7(this)};
g.k.da=function(){g.yo(this.subscriptions);g.hN.prototype.da.call(this)};
g.k.rj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.lh.SB.apply(this.lh,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.Me};
g.k.pL=function(){return this.loaded?this.lh.suggestion:null};
g.k.aj=function(){return this.xb?v6(this.xb).aj:!1};
g.k.hasNext=function(){return this.xb?v6(this.xb).hasNext:!1};
g.k.Db=function(a,b){this.zE=a||0;this.player.V("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.zE};
g.k.getProgressState=function(){var a=v6(this.xb),b=this.player.getVideoData();return{allowSeeking:g.U(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Ke():!a.isAdPlaying()&&this.player.Ke(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+o6(a):a.B,isAtLiveHead:1>=(a.u?a.l+o6(a):a.l)-this.getCurrentTime(),loaded:a.W,seekableEnd:a.u?a.l+o6(a):a.l,seekableStart:0<a.C?a.C+
o6(a):a.C}};
g.k.nextVideo=function(){this.xb&&this.xb.nextVideo()};
g.k.Ou=function(){this.xb&&this.xb.Ou()};
g.k.bN=function(a){1===a&&(this.Ez=this.xb?v6(this.xb):null)};
g.k.IO=function(){var a=$6()?new u6(U6(),void 0):null;if(a){var b=this.Yk;this.loaded&&this.unload();this.xb=a;this.Ez=null;b.key!==this.di.key&&(this.Yk=b,this.load())}else g.zi(this.xb),this.xb=null,this.loaded&&(this.unload(),(a=this.Ez)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,q6(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.RF=function(){var a=[this.di],b=a.concat,c=uKa();i6()&&g.Hu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Nl=b.call(a,c);a=V6()||this.di;m7(this,a);this.player.xa("onMdxReceiversChange")};
g.k.GO=function(){var a=V6();m7(this,a)};
g.k.FO=function(){this.Yk=V6()};
g.k.WP=function(){this.Lr=!0;l7(this);b7=!1;W6&&Y6(W6,1);W6=null};
g.k.VP=function(){this.Lr=!1;l7(this);m7(this,this.di);this.Yk=this.di;b7=!1;W6=null;this.player.playVideo()};
g.k.kM=function(){this.pu=!0;l7(this);g.Gu("yt-remote-manual-pairing-warning-shown",!0,2592E3);b7=!1;W6&&Y6(W6,1);W6=null};
g.k.Fe=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Nl;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?k6():m7(this,b)),this.loaded?this.Yk:this.di;case "quickCast":return 2===this.Nl.length&&"cast-selector-receiver"===this.Nl[1].key?(b&&k6(),!0):!1}};
g.k.tA=function(){this.xb.tA()};
g.k.yi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.nN.remote=k7;})(_yt_player);
